### PR TITLE
Fixes malformed error message for Vavr assertions

### LINKED ISSUE #122: Assertion error message for containsOnLeft doesn't contain actual left value
# Description
#50 hasn't completely fixed assertion error messages on `Either`, because of this line in assertj-core's [`StandardRepresentation`](https://github.com/assertj/assertj-core/blob/3f654ef0d30225e3d820967f478c5582fba82121/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L218):
```java
    if (object instanceof Iterable<?>) return smartFormat((Iterable<?>) object);
```
This might affect other assertion error messages, too.

# Example
```java
assertThat(Either.left("hello")).containsOnLeft("hello world");
```
## Expected Behavior
leads to an assertion error message containing the actual value, f.i. like

> Expecting:
>  <"Left(hello)">
> to contain:
>  <"hello world"> on the [LEFT]
> but did not.

## Actual Behavior
leads to assertion error message

> Expecting:
>  <[]>
> to contain:
>  <"hello world">
> but did not.

# Tested with
- assertj-vavr 0.2.0

### PR DESCRIPTION
**Pull request by mchmielarz**
Fixes #122

### CODE REVIEW

**Review by Opalo — APPROVED** [review]

**Comment by mchmielarz** [comment]
@pivovarit Could you look at it?

**Comment by pivovarit** [comment]
On my list for tomorrow

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        if (object instanceof Either) return toStringOf((Either<?, ?>) object);
+        if (object instanceof Try) return toStringOf((Try<?>) object);
+        if (object instanceof Validation) return toStringOf((Validation<?, ?>) object);
+        return super.toStringOf(object);
+    }
+
+    private String toStringOf(Either<?, ?> either) {
+        return either.fold(
+                v -> v == null ? "null" : String.format("Left(%s)", v),
+                v -> v == null ? "null" : String.format("Right(%s)", v));
```
Comment (sesamzoo) [inline src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:34]: Wouldn't it make sense to use
```java
return either.toString();
```
which results in the same output?

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    private String toStringOf(Try<?> aTry) {
+        return aTry.fold(
+                v -> v == null ? "null" : String.format("Failure(%s)", v),
+                v -> v == null ? "null" : String.format("Success(%s)", v));
```
Comment (sesamzoo) [inline src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:40]: Could be replaced by
```java
return aTry.toString();
```

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    private String toStringOf(Validation<?, ?> validation) {
+        return validation.fold(
+                v -> v == null ? "null" : String.format("Invalid(%s)", v),
+                v -> v == null ? "null" : String.format("Valid(%s)", v));
```
Comment (sesamzoo) [inline src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:46]: Could be replaced by
```java
validation.toString();
```

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 1 above)
Comment (pivovarit) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:34]: Totally agreed. We should go for:
```suggestion
        return either.toString();
```

And the same should be applied to similar cases

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+public class VavrRepresentation extends StandardRepresentation {
+
+    @Override
+    public String toStringOf(Object object) {
+        if (object == null) return null;
+        if (object instanceof Either) return toStringOf((Either<?, ?>) object);
+        if (object instanceof Try) return toStringOf((Try<?>) object);
+        if (object instanceof Validation) return toStringOf((Validation<?, ?>) object);
+        return super.toStringOf(object);
+    }
```
Comment (pivovarit) [inline src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:29]:
```suggestion
    @Override
    public String toStringOf(Object object) {
        if (object instanceof Either
            || object instanceof Try
            || object instanceof Validation) {
                return object.toString();
          }
          return super.toStringOf(object);
    }
```

Actually, since we don't really need helper methods, this should do it.

**Review by pivovarit — CHANGES_REQUESTED** [review]

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 4 above)
Comment (sesamzoo) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:29]: I think `Option` should be handled as well. Otherwise it's treated as an `Iterable` by `super.toStringOf(object)`.

**Comment by sesamzoo** [comment]
Actually, this PR could be replaced by upgrading to [assertj-core 3.18.0 (see _Fixed_ section)](https://assertj.github.io/doc/#assertj-core-3-18-0-release-notes) because `StandardRepresentation` has been changed to
> Honor toString if overridden in Iterable that are not collections.

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 1 above)
Comment (mchmielarz) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java]: Good hint!

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 2 above)
Comment (mchmielarz) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:39]: ****

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 3 above)
Comment (mchmielarz) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java:45]: Good hint!

File: src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java (hunk 4 above)
Comment (mchmielarz) [reply src/main/java/org/assertj/vavr/internal/error/VavrRepresentation.java]: Good hint!

**Comment by mchmielarz** [comment]
@sesamzoo Yeah, t should. It didn't because of formatting error messages in message factories. I will update them and we won't need a special representation for Vavr

**Comment by mchmielarz** [comment]
@pivovarit @sesamzoo Updated!

**Comment by mchmielarz** [comment]
@pivovarit ping

**Review by pivovarit — APPROVED** [review]
